config/routes.rb
Rails.application.routes.draw do
  resources :repositories
  devise_for :people, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :pull_requests
  post 'github/webhooks' => "messages#create"
  resources :messages

  root 'repositories#index'

end

app/models/repository.rb
class Repository < ActiveRecord::Base
  serialize :data, Hash
  belongs_to :person
  has_many :pull_requests, foreign_key: :repo_id

  def client
    @client ||= self.person.github_client
  end

  def github_repo
    client.repo self.full_name
  end

  def hooks
    github_repo.rels[:hooks].get
  end

  def create_rebaser_hook
    create_hook("web", ["pull_request"], "https://pacific-ocean-45584.herokuapp.com/github/webhooks/")
  end

  def create_hook(name, events, url)
    hook_data = {
      "name": name,
      "active": true,
      "events": events,
      "config": {
        "url": url,
        "content_type": "json"
      }
    }
    client.post(github_repo.rels[:hooks].href,hook_data)
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :authenticate_person!
  before_action :set_repository, only: [:edit, :update, :destroy]

  # GET /repositories
  # GET /repositories.json
  def index
    repositories = current_person.github_client.repos + current_person.github_client.orgs.map { |o| o.rels[:repos].get.data }.flatten
    @repositories = repositories.group_by { |r| r.owner.login }
  end

  # GET /repositories/1
  # GET /repositories/1.json
  def show
    @repository = Repository.find_by(full_name: URI.decode(params[:id])) ||
      Repository.find_by(id: params[:id]) ||
      Repository.new(person: current_person, full_name: params[:id])
    @repository.save
  end

  # GET /repositories/new
  def new
    @repository = Repository.new
  end

  # GET /repositories/1/edit
  def edit
  end

  # POST /repositories
  # POST /repositories.json
  def create
    full_name = params[:repository][:full_name]
    repository_params = current_person.github_client.repos.find {|r| r.full_name == full_name }
    @repository = Repository.new(
      person: current_person,
      ssh_url: repository_params.rels[:ssh].href,
      full_name: full_name,
      data: JSON.parse(repository_params.to_json)
    )

    respond_to do |format|
      if @repository.save
        format.html { redirect_to @repository, notice: 'Repository was successfully created.' }
        format.json { render json: @repository, status: :created, location: @repository }
      else
        format.html { render :new }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repositories/1
  # PATCH/PUT /repositories/1.json
  def update
    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to @repository, notice: 'Repository was successfully updated.' }
        format.json { render :show, status: :ok, location: @repository }
      else
        format.html { render :edit }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.json
  def destroy
    @repository.destroy
    respond_to do |format|
      format.html { redirect_to repositories_url, notice: 'Repository was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repository
      @repository = Repository.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repository_params
      params.require(:repository).permit(:user_id, :name)
    end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/repositories/_form.html.erb
<%= form_for(@repository) do |f| %>
  <% if @repository.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repository.errors.count, "error") %> prohibited this repository from being saved:</h2>

      <ul>
      <% @repository.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repositories/edit.html.erb
<h1>Editing Repository</h1>

<%= render 'form' %>

<%= link_to 'Show', @repository %> |
<%= link_to 'Back', repositories_path %>

app/views/repositories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Repositories</h1>

<% @repositories.each do |group, repositories| %>
  <h2><%= group %></h2>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% repositories.each do |repository| %>
        <tr>
          <td><%= repository.full_name %></td>
          <td><%= link_to 'Show', repository_path(id: repository.full_name) %></td>
          <td><%= link_to 'Edit', edit_repository_path(repository) %></td>
          <td><%= link_to 'Destroy', repository_path(id: repository.full_name), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<br>

<%= link_to 'New Repository', new_repository_path %>

app/views/repositories/new.html.erb
<h1>New Repository</h1>

<%= render 'form' %>

<%= link_to 'Back', repositories_path %>

app/views/repositories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>URL:</strong>
  <a href="<%= @repository.github_repo.rels[:html].href + '/settings/hooks' %>">Github</a>
</p>

<p>
  <strong>User:</strong>
  <%= @repository.person.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @repository.full_name %>
</p>

<p>
  <strong>Hooks:</strong>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>URL</th>
      </tr>
    </thead>

    <tbody>
  <% @repository.hooks.data.each do |hook| %>
      <tr>
        <td><%= hook.name %></td>
        <td><%= hook.config.rels[:self].try(:href) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_repository_path(@repository) %> |
<%= link_to 'Back', repositories_path %>