config/routes.rb
Rails.application.routes.draw do
  resources :repositories
  devise_for :people, :controllers => { :omniauth_callbacks => "callbacks" }
  resources :pull_requests
  post 'github/webhooks' => "messages#create"
  resources :messages

  root 'repositories#index'

end

app/models/github/pull_request.rb
module Github
  class PullRequest
    def self.create(branch)
      owner = 'deanmarano'
      repo = 'my-test-repo'
      body = {
        "title": "Amazing new feature",
        "body": "Please pull this in!",
        "head": branch,
        "base": "master"
      }
      Person.first.github_client.post("/repos/#{owner}/#{repo}/pulls", body)
    end
  end
end

app/models/pull_request.rb
class PullRequest < ActiveRecord::Base
  belongs_to :repository, foreign_key: :repo_id
  serialize :data, Hash
end

app/controllers/pull_requests_controller.rb
class PullRequestsController < ApplicationController
  before_action :set_pull_request, only: [:show, :edit, :update, :destroy]

  # GET /pull_requests
  # GET /pull_requests.json
  def index
    @pull_requests = PullRequest.all
  end

  # GET /pull_requests/1
  # GET /pull_requests/1.json
  def show
  end

  # GET /pull_requests/new
  def new
    @pull_request = PullRequest.new
  end

  # GET /pull_requests/1/edit
  def edit
  end

  # POST /pull_requests
  # POST /pull_requests.json
  def create
    @pull_request = PullRequest.new(pull_request_params)

    respond_to do |format|
      if @pull_request.save
        format.html { redirect_to @pull_request, notice: 'Pull request was successfully created.' }
        format.json { render :show, status: :created, location: @pull_request }
      else
        format.html { render :new }
        format.json { render json: @pull_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pull_requests/1
  # PATCH/PUT /pull_requests/1.json
  def update
    respond_to do |format|
      if @pull_request.update(pull_request_params)
        format.html { redirect_to @pull_request, notice: 'Pull request was successfully updated.' }
        format.json { render :show, status: :ok, location: @pull_request }
      else
        format.html { render :edit }
        format.json { render json: @pull_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pull_requests/1
  # DELETE /pull_requests/1.json
  def destroy
    @pull_request.destroy
    respond_to do |format|
      format.html { redirect_to pull_requests_url, notice: 'Pull request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pull_request
      @pull_request = PullRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pull_request_params
      params.fetch(:pull_request, {})
    end
end

app/helpers/pull_requests_helper.rb
module PullRequestsHelper
end

app/views/pull_requests/_form.html.erb
<%= form_for(@pull_request) do |f| %>
  <% if @pull_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pull_request.errors.count, "error") %> prohibited this pull_request from being saved:</h2>

      <ul>
      <% @pull_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pull_requests/edit.html.erb
<h1>Editing Pull Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @pull_request %> |
<%= link_to 'Back', pull_requests_path %>

app/views/pull_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pull Requests</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pull_requests.each do |pull_request| %>
      <tr>
        <td><%= link_to 'Show', pull_request %></td>
        <td><%= link_to 'Edit', edit_pull_request_path(pull_request) %></td>
        <td><%= link_to 'Destroy', pull_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pull request', new_pull_request_path %>

app/views/pull_requests/new.html.erb
<h1>New Pull Request</h1>

<%= render 'form' %>

<%= link_to 'Back', pull_requests_path %>

app/views/pull_requests/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_pull_request_path(@pull_request) %> |
<%= link_to 'Back', pull_requests_path %>